title: Ezpie Read tech blogs
email: ezpie.co@gmail.com
description: >-
  Ezpie Read blogs do challenges and a hole lot more. With just one click
  you can learn all about python, javascript, go, and other programming languages
baseurl: "/ezpie"
url: "https://ishaan010.github.io"
twitter_username: EzpieCo
github_username: ishaan010

exclude:
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE
  - .gitignore
  - .all-contrbutorsrc
  - .github
