title: Ezpie
email: ezpie.co@gmail.com
description: Ezpie learn programming for free with challenges
url: "https://ishaan010.github.io/"

markdown: kramdown

sass:
  sass_dir: _sass

exclude:
  - README.md
  - LICENSE
  - CODE_OF_CONDUCT.md
  - CONTRIBUTING.md
  - Gemfile
  - Gemfile.lock
  - .github/
  - .gitignore
  - vendor
