title: Ezpie
email: ezpie.co@gmail.com
description: Ezpie learn programming for free with challenges
baseurl: "ezpie/"
url: "https://ishaan010.github.io/"
twitter_username: jekyllrb
github_username: jekyll

markdown: kramdown

sass:
  sass_dir: _sass
