name: "Automatic build"
on:
  push:
    branches:
      - master
    paths-ignore:
      - .gitignore
      - README.md
      - LICENSE
      - Gemfile
      - .all-contributorsrc
      - CODE_OF_CONDUCT.md

jobs:
  continuous-delivery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.5.0
        with:
          fetch-depth: 0

      - name: Setup Ruby
        uses: ruby/setup-ruby@v1.1.3
        with:
          ruby-version: 3.1.2
          bundler-cache: true

      - name: Deploy
        run: bash tools/deploy.sh
